User can buy a subscription
CraftAcademy/newsroom_team2_news_app pull request #10
Opened 2020-03-29 14:25 UTC by kfrostare

# [PT Story](https://www.pivotaltracker.com/story/show/171811174)
```
As a user 
In order to get access to the best articles
I would like to be able to buy a subscription
```
## Changes proposed in this pull request:
* 

## What I have learned working on this feature:
*  

## Packages/Gems added
-
-

## Screenshots (Only if client side story)

2020-03-29 20:27 UTC, JaimeCrz requested changes
Checked, changes requested.

2020-03-29 20:27 UTC, JaimeCrz commented on cypress/integration/userCanPayForSubscription.feature.js
> +
Since it's the before block we can take this line away.

2020-03-29 20:27 UTC, JaimeCrz commented on src/components/PaymentForm.jsx
> +
line 22 indentation (delete it please)

2020-03-29 20:27 UTC, JaimeCrz commented on cypress/integration/userCanPayForSubscription.feature.js
> +
indentation. You can probably delete this line as it's part of the before block

2020-03-29 20:27 UTC, JaimeCrz commented on src/index.js
>  // axios.defaults.baseURL = "https://urban-living.herokuapp.com/api/";
Use the herokuapp link on the PR.

2020-03-29 20:27 UTC, JaimeCrz commented on src/index.js
> +	<StripeProvider apiKey="pk_test_UmHwHMrhpkYb9JMGFx29IehA00HEZ8ErkY">
Probably we should hide this key somehow?

Info here:

https://stackoverflow.com/questions/48699820/how-do-i-hide-api-key-in-create-react-app
 
and: 

https://www.youtube.com/watch?v=17UVejOw3zA&list=PLRqwX-V7Uu6YxDKpFzf_2D84p0cyk4T7X&t=307s

https://www.youtube.com/watch?v=Rz886HkV1j4&list=PLRqwX-V7Uu6YxDKpFzf_2D84p0cyk4T7X&t=0s

(Keep in mind we are using netlify.)
https://docs.netlify.com/configure-builds/environment-variables/

2020-03-30 09:16 UTC, JaimeCrz approved these changes
LGTM!

2020-03-30 09:27 UTC, johanbounce commented
Go

2020-03-30 09:28 UTC, merged