[WIP] user can see specific article
CraftAcademy/newsroom_team2_news_app pull request #5
Opened 2020-03-21 11:01 UTC by blake-futchi

2020-03-21 12:54 UTC, JaimeCrz requested changes

2020-03-21 12:54 UTC, JaimeCrz commented on cypress/fixtures/specific_article.json
> +  "articles": [
The response it's not wrapped by "articles" as we sent you guys before in slack.

![image](https://user-images.githubusercontent.com/59778082/77226749-fd6a3680-6b7a-11ea-9e1f-0093c860c803.png)

2020-03-21 14:24 UTC, robin-lillqvist requested changes

2020-03-21 14:24 UTC, robin-lillqvist commented on cypress/fixtures/specific_article1.json
> +  "articles": [
what is this file even doing?

2020-03-21 21:00 UTC, robin-lillqvist requested changes

2020-03-21 21:00 UTC, robin-lillqvist commented on cypress/integration/userCanSeeSpecificArticle.feature.js
> +      cy.get("button").contains("Read More").click()
We aren't testing any specific content here, so this could be any article really

2020-03-21 21:00 UTC, robin-lillqvist commented on src/state/actions/articleActions.js
> +		let response = await axios.get(apiURL)
intendation here please

2020-03-23 08:55 UTC, robin-lillqvist approved these changes

2020-03-23 08:56 UTC, robin-lillqvist commented
LGTM

2020-03-23 08:56 UTC, JaimeCrz approved these changes

2020-03-23 08:57 UTC, merged

2020-03-23 08:57 UTC, robin-lillqvist commented
MERGED!